import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
    lineHeight: 1.5,
  },
  title: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 30,
    textTransform: 'uppercase',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    marginBottom: 8,
    paddingBottom: 2,
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  label: {
    width: '30%',
    fontWeight: 'bold',
    fontSize: 10,
    color: '#444',
  },
  value: {
    width: '70%',
    fontSize: 10,
  },
  // Result Box
  resultBox: {
    borderWidth: 1,
    borderColor: '#000',
    padding: 15,
    marginTop: 10,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
  },
  resultLabel: {
    fontSize: 10,
    color: '#666',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  resultValue: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  
  // Helpers
  green: { color: 'green' },
  red: { color: 'red' },
  
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    textAlign: 'center',
    color: '#888',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 10,
  }
});

export default function ExamReportPDF({ student, supervisor, exam, result }: any) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        {/* Title */}
        <Text style={styles.title}>Examination Report</Text>

        {/* Candidate Details */}
        <View style={styles.section}>
            <Text style={styles.sectionTitle}>Candidate Details</Text>
            <View style={styles.row}>
                <Text style={styles.label}>Full Name:</Text>
                <Text style={styles.value}>{student.name}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Company:</Text>
                <Text style={styles.value}>{student.company || 'N/A'}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Email:</Text>
                <Text style={styles.value}>{student.email}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Phone:</Text>
                <Text style={styles.value}>{student.phone}</Text>
            </View>
        </View>

        {/* Exam Details */}
        <View style={styles.section}>
            <Text style={styles.sectionTitle}>Assessment Details</Text>
            <View style={styles.row}>
                <Text style={styles.label}>Exam Title:</Text>
                <Text style={styles.value}>{exam.title}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Supervisor:</Text>
                <Text style={styles.value}>{supervisor.name}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Date:</Text>
                <Text style={styles.value}>{exam.date}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Access ID:</Text>
                <Text style={styles.value}>{exam.id}</Text>
            </View>
        </View>

        {/* Result Summary Box */}
        <View style={styles.section}>
            <Text style={styles.sectionTitle}>Performance Summary</Text>
            
            <View style={styles.resultBox}>
                <View>
                    <Text style={styles.resultLabel}>Final Score</Text>
                    <Text style={styles.resultValue}>{result.score} / {result.totalMarks}</Text>
                </View>
                <View style={{ alignItems: 'center' }}>
                    <Text style={styles.resultLabel}>Percentage</Text>
                    <Text style={styles.resultValue}>{result.percentage}%</Text>
                </View>
                <View style={{ alignItems: 'flex-end' }}>
                    <Text style={styles.resultLabel}>Status</Text>
                    <Text style={[styles.resultValue, result.status === 'PASS' ? styles.green : styles.red]}>
                        {result.status}
                    </Text>
                </View>
            </View>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
            Generated by ExamPortal - Official Record
        </Text>

      </Page>
    </Document>
  );
}